name: Bug Report
description: "Report an issue with MEGAcmd"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thank you for filing a bug report!"
  - type: dropdown
    id: version
    attributes:
      label: "MEGAcmd version"
      description: "Which version of MEGAcmd did you encountered this issue? (Can be looked up using the `version` command)"
      options:
        - 1.6.3
        - 1.6.2
        - 1.6.1
        - 1.6.0
        - 1.5.1
        - 1.5.0
        - 1.4.1
        - 1.3.0
        - 1.2.0
        - 1.1.0
        - 1.0.0
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: "Operating System/Platform"
      description: "What platform are you using MEGAcmd on?"
      options:
        - Windows
        - Linux
        - MacOS
        - Synology
        - QNAP
    validations:
      required: true
  - type: input
    id: platform-version
    attributes:
      label: "Platform version. In the case of Linux, please enter the Linux distribution you are using."
      placeholder: "ex. Windows 11 Pro"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps"
      description: "What steps did you take you encounter this issue?"
      placeholder: |
        1.
        2.
        3.
        4.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual behavior"
      description: "What actually happened?"
    validations:
      required: true
